# Generated by Django 5.0.2 on 2025-12-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('edificio', models.CharField(max_length=255)),
                ('aula', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
                ('recursos_json', models.TextField(blank=True, default='[]', null=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
