# Generated by Django 5.0.2 on 2025-11-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
