# Generated by Django 5.0.2 on 2025-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0002_administradores_biografia_administradores_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
