# Generated by Django 5.0.2 on 2025-12-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0002_alter_evento_organizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
