# Generated by Django 5.0.2 on 2025-12-04 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0002_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('inscrito', 'Inscrito'), ('cancelado_usuario', 'Cancelado por Usuario'), ('cancelado_organizador', 'Cancelado por Organizador')], default='inscrito', max_length=50)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('asistencia', models.CharField(choices=[('pendiente', 'Pendiente'), ('asistio', 'Asistió'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=20)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='sistema_gtea.estudiantes')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='sistema_gtea.evento')),
            ],
        ),
    ]
