# Generated by Django 5.0.2 on 2025-11-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0003_estudiantes_biografia_estudiantes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizador',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
