# Generated by Django 5.0.2 on 2025-12-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0003_alter_evento_organizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_eventos', to='sistema_gtea.organizador'),
        ),
    ]
