# Generated by Django 5.0.2 on 2025-12-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0004_organizador_email_organizador_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='publico_json',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
