# Generated by Django 5.0.2 on 2025-03-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0005_Organizador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Organizador',
            old_name='materia',
            new_name='materias',
        ),
    ]
