# Generated by Django 5.0.2 on 2025-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0005_alter_evento_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nombre_organizador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
