# Generated by Django 5.0.2 on 2025-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_gtea', '0007_rename_area_Organizador_area_investigacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Organizador',
            name='materias',
        ),
        migrations.AddField(
            model_name='Organizador',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
